In [1]:
import pandas as pd
import numpy as np

In [2]:
df  = pd.read_excel('ML_Preprocessing_Practice_Dataset.excel')

In [3]:
df.head()

,Education_Level,City,Department,Employment_Type,Age,Monthly_Income,Performance
0,High School,Hyderabad,Marketing,Part-Time,27.0,21250.0,Average
1,Bachelor,Chennai,Sales,Part-Time,24.0,45231.0,Average
2,High School,Chennai,Sales,Contract,36.0,25366.0,Average
3,High School,Bengaluru,IT,Contract,45.0,22289.0,Average
4,High School,Bengaluru,IT,Full-Time,26.0,24658.0,Average

In [4]:
df.isnull().sum()

Education_Level     6
City               13
Department         11
Employment_Type     8
Age                15
Monthly_Income      7
Performance         0
dtype: int64

### ***Here Performance column is treating as target column so we will apply lable encoding on performance column***

In [11]:
df['Performance'].unique()

array(['Average', 'Good', 'Excellent'], dtype=object)

In [12]:
df['Performance'].isnull().sum()

0

# ***Manual Lable Encoding***

In [13]:
# Create a Mapping Dictionary
# Assign a unique label to each category.

performance_mapping = {
    "Average": 0,
    "Good": 1,
    "Excellent": 2
}

In [14]:
# Apply the Mapping
df["Performance"] = df["Performance"].map(performance_mapping)

In [16]:
df['Performance'].unique()

array([0, 1, 2], dtype=int64)

# ***Lable Encoding using LableEncoder  Class***
- always apply lable encoder after train test split to prevent data Leakage, here we are just learnign the concept.

#### ***Reload the dataset first because we have already encoded the Performance column manually.***

In [17]:
df  = pd.read_excel('ML_Preprocessing_Practice_Dataset.excel')

In [20]:
from sklearn.preprocessing import LabelEncoder

In [21]:
le = LabelEncoder()

In [24]:
df["Performance"] = le.fit_transform(df['Performance'])

In [25]:
df['Performance']

0       0
1       0
2       0
3       0
4       0
       ..
5525    2
5526    0
5527    2
5528    2
5529    0
Name: Performance, Length: 5530, dtype: int32

In [26]:
df.head()

,Education_Level,City,Department,Employment_Type,Age,Monthly_Income,Performance
0,High School,Hyderabad,Marketing,Part-Time,27.0,21250.0,0
1,Bachelor,Chennai,Sales,Part-Time,24.0,45231.0,0
2,High School,Chennai,Sales,Contract,36.0,25366.0,0
3,High School,Bengaluru,IT,Contract,45.0,22289.0,0
4,High School,Bengaluru,IT,Full-Time,26.0,24658.0,0

In [28]:
le.classes_

array(['Average', 'Excellent', 'Good'], dtype=object)

In [ ]:
# This confirms that LabelEncoder assigns labels in alphabetical order:
Average   → 0
Excellent → 1
Good      → 2

### ***You can also convert the encoded values back to their original categories:***

In [31]:
le.inverse_transform([0, 1, 2])

array(['Average', 'Excellent', 'Good'], dtype=object)